experiment_name: "simmim_pretrain_swin_tiny_v2_patch4"

model:
  backbone: "swinv2_tiny_window16_256"
  input_size: 256

data:
  batch_size: 32
  num_workers: 4
  mask_patch_size: 4 
  mask_ratio: 0.65    
  in_channels: 1    
 

optimizer:
  lr: 1e-4            
  weight_decay: 0.05
  epochs: 300           

system:
  device: "cuda"
  seed: 42
  save_dir: "./checkpoints/mim/"