experiment_name: "simmim_pretrain_vit_small_patch16_224_v1"

model:
  backbone: "vit_small_patch16_224"
  input_size: 256

data:
  batch_size: 20        
  num_workers: 0       
  mask_patch_size: 8 
  mask_ratio: 0.5     
  in_channels: 1    
 

optimizer:
  lr: 1e-4            
  weight_decay: 0.05
  epochs: 100           

system:
  device: "cuda"
  seed: 42
  save_dir: "./checkpoints/mim/"