experiment_name: "simmim_pretrain_vit_small_patch16_224"

model:
  backbone: "vit_small_patch16_224"
  input_size: 256

data:
  batch_size: 32
  num_workers: 4
  mask_patch_size: 4 
  mask_ratio: 0.65    
  in_channels: 1    
 

optimizer:
  lr: 1e-4            
  weight_decay: 0.05
  epochs: 300           

system:
  device: "cuda"
  seed: 42
  save_dir: "./checkpoints/mim/"