experiment_name: "unext_s_segmentation_v1"

model:
  name: "UNeXt_S"
  in_channels: 1
  num_classes: 1
  input_size: 256
  base_channels: 32
  depths: [1, 1, 1, 1, 1]
  mlp_ratio: 4
  drop_rate: 0.5

data:
  dataset_json: "D:\\Collateral Coronary Vessels XAI\\data\\Segmentation Data\\dataset.json"
  batch_size: 8
  num_workers: 4

optimizer:
  lr: 1e-4
  weight_decay: 1e-4
  epochs: 100

system:
  device: "cuda"
  seed: 42
  save_dir: "./checkpoints/unext/"